AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*
    - gemfiles/vendor/**/*
    - tmp/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CommentIndentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
    Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  Enabled: false

# sometimes the most readable way of doing things
Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: percent

# for simple cases more readable
Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodName:
  Exclude:
    - lib/kasket/visitor.rb

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PredicateName:
  Enabled: false

# for single `/` more readable
Style/RegexpLiteral:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

# nice for .with{} mock stubs
Style/Semicolon:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Style/WordArray:
  Enabled: false
