rvm:
  - 1.9.3
  - 2.0
  - jruby
gemfile:
  - gemfiles/activerecord_2.3.gemfile
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/activerecord_2.3.gemfile
