script: bundle exec rake test
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - jruby
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
branches:
  only: [master]
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails4.2.gemfile
